src/config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from crypto.urls import crypto_patterns, crypto_patterns_api
from deposits.urls import deposits_patterns, deposits_drf_patterns
from deposits.views import RegisterUser, LoginUser, HomePage, logout_user
from portfolio.urls import portfolio_patterns
from stocks.urls import stocks_patterns, stocks_patterns_api

urlpatterns = [
    path('admin/', admin.site.urls),

    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),

    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('main/', HomePage.as_view(), name='home'),

    path('stocks/', include((stocks_patterns, 'stocks'))),
    path('deposits/', include((deposits_patterns, 'deposits'))),
    path('crypto/', include((crypto_patterns, 'crypto'))),
    path('portfolio/', include((portfolio_patterns, 'portfolio'))),

    path('api/v1/crypto/', include(crypto_patterns_api)),
    path('api/v1/', include(stocks_patterns_api)),
    path('api/v1/', include(deposits_drf_patterns))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/crypto/urls.py
from django.urls import path
from crypto.views import CryptoBalance, CryptoAddTransactions, CryptoHistoryTransactions, CryptoPersonBalance, \
    add_transaction, add_invest_sum, PersonCryptoEdit, PersonCryptoTransaction, PersonCryptoTransactionEdit, \
    PersonCryptoTransactionDelete

app_name = 'crypto'

crypto_patterns_api = [
    path('', CryptoBalance.as_view(), name='crypto_api'),
    path('add/', CryptoAddTransactions.as_view(), name='add_crypto'),
    path('history/', CryptoHistoryTransactions.as_view()),
    ]

crypto_patterns = [
    path('', CryptoPersonBalance.as_view(), name='crypto'),
    path('<int:pk>/', PersonCryptoEdit.as_view(), name='person_crypto_edit'),

    path('transactions/', PersonCryptoTransaction.as_view(), name='person_crypto_transactions'),
    path('transactions/<int:pk>/', PersonCryptoTransactionEdit.as_view(), name='person_crypto_transaction_edit'),
    path('transactions/<int:pk>/delete/', PersonCryptoTransactionDelete.as_view(), name='person_crypto_transaction_delete'),


    path('add_crypto/', add_transaction, name='add_crypto'),
    path('add_invest/', add_invest_sum, name='add_invest')
    ]

src/portfolio/urls.py
from django.urls import path, include
from rest_framework import routers


app_name = 'portfolio'

portfolio_patterns = [
    # path('', UserPortfolio.as_view(), name='portfolio'),
    # path('add/', add_stock_transaction, name='add_portfolio')
]

src/portfolio/templates/portfolio/add_portfolio.html
{% extends 'base.html' %}
{% block content %}

<p>
    <div>
</div>
</p>

<a class="btn btn-primary" href="{% url 'crypto:crypto' %}" role="button">Баланс</a>

<p>
    <div>
</div>
</p>

<ul class="list-articles">
 <form method="post">
        {%csrf_token%}
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <button type="submit"> Добавить </button>
    </form>

</ul>

{%endblock%}

src/portfolio/templates/portfolio/portfolio.html
{% extends 'base.html' %}
{% block content %}

<p>
<div>

</div>
</p>


<a class="btn btn-primary" href="{% url 'crypto:add_crypto' %}" role="button">Добавить портфель</a>




<table class="table">
    <thead>
    <tr>
        <th scope="col"></th>
        <th scope="col">
           <p class="h5">Баланс {{  balance.total_balance_in_rub}} ₽</p>
            <p class="h6">Прибыль {{ balance.profit_in_currency_rub}} ₽   {{balance.profit_in_percents_rub}} %</p>

        </th>
        <th scope="col">
          <p class="h5">Баланс {{ balance.total_balance_in_usd}} $</p>
            <p class="h6">Прибыль {{ balance.profit_in_currency_usd}} $   {{ balance.profit_in_percents_usd}} %</p>

        </th>
        <th scope="col">
            <p class="h5">Доля в портфеле</p>
        </th>
    </tr>
    </thead>
    <tbody>
    {% for value in object_list %}
    <tr>
        <th scope="row"> {{ value.name}}</th>
        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ value.name.upper }}
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {{ value.lot }} шт. &nbsp {{ value.current_price }} {{value.currency}}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-right">
                <div class="row">
                    <div class="col">
                        Баланс {{ value.total_now_balance }} {{value.currency}}
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        {{ value.profit_in_currency }} {{value.currency}} &nbsp {{ value.profit_in_percent }}%
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-right">
                <div class="row">
                    <div class="col">
                        {{ value.percent_of_portfolio}} %
                    </div>
                </div>

            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>


{%endblock%}