src/config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from crypto.urls import crypto_patterns, crypto_patterns_api
from deposits.urls import deposits_patterns, deposits_drf_patterns
from deposits.views import RegisterUser, LoginUser, HomePage, logout_user
from portfolio.urls import portfolio_patterns
from stocks.urls import stocks_patterns, stocks_patterns_api

urlpatterns = [
    path('admin/', admin.site.urls),

    path('api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),

    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('main/', HomePage.as_view(), name='home'),

    path('stocks/', include((stocks_patterns, 'stocks'))),
    path('deposits/', include((deposits_patterns, 'deposits'))),
    path('crypto/', include((crypto_patterns, 'crypto'))),
    path('portfolio/', include((portfolio_patterns, 'portfolio'))),

    path('api/v1/crypto/', include(crypto_patterns_api)),
    path('api/v1/', include(stocks_patterns_api)),
    path('api/v1/', include(deposits_drf_patterns))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/crypto/urls.py
from django.urls import path
from crypto.views import CryptoBalance, CryptoAddTransactions, CryptoHistoryTransactions, CryptoPersonBalance, \
    add_transaction, add_invest_sum, PersonCryptoEdit, PersonCryptoTransaction, PersonCryptoTransactionEdit, \
    PersonCryptoTransactionDelete

app_name = 'crypto'

crypto_patterns_api = [
    path('', CryptoBalance.as_view(), name='crypto_api'),
    path('add/', CryptoAddTransactions.as_view(), name='add_crypto'),
    path('history/', CryptoHistoryTransactions.as_view()),
    ]

crypto_patterns = [
    path('', CryptoPersonBalance.as_view(), name='crypto'),
    path('<int:pk>/', PersonCryptoEdit.as_view(), name='person_crypto_edit'),

    path('transactions/', PersonCryptoTransaction.as_view(), name='person_crypto_transactions'),
    path('transactions/<int:pk>/', PersonCryptoTransactionEdit.as_view(), name='person_crypto_transaction_edit'),
    path('transactions/<int:pk>/delete/', PersonCryptoTransactionDelete.as_view(), name='person_crypto_transaction_delete'),


    path('add_crypto/', add_transaction, name='add_crypto'),
    path('add_invest/', add_invest_sum, name='add_invest')
    ]

src/crypto/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class PersonsCrypto(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    token = models.CharField(max_length=16, verbose_name='Токен')
    lot = models.FloatField(verbose_name="Количество")
    average_price_in_rub = models.FloatField(default=0, verbose_name="Средняя цена в рублях")
    average_price_in_usd = models.FloatField(default=0, verbose_name="Средняя цена в $")

    def __str__(self):
        return str(self.user) + '  ' + str(self.token)


class PersonsTransactions(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=3)
    is_buy_or_sell = models.BooleanField(verbose_name='Покупка')
    token_1 = models.CharField(max_length=16, verbose_name="Первый токен")
    token_2 = models.CharField(max_length=16, verbose_name="Второй токен")
    price_in_rub = models.FloatField(default=0, verbose_name="Цена в рублях")
    price_in_usd = models.FloatField(default=0, verbose_name="Цена в $")
    lot = models.FloatField(verbose_name="Количество")
    date_operation = models.DateField(default=timezone.now(), verbose_name="Дата транзакции")

    def __str__(self):
        return f'{self.token_1} {self.user.username} {self.date_operation}'


class CryptoInvest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='crypto_invest')
    invest_sum_in_rub = models.FloatField()
    invest_sum_in_usd = models.FloatField()
    date_operation = models.DateField(default=timezone.now())

    def __str__(self):
        return f'{str(self.user)} {self.invest_sum_in_rub} руб {self.invest_sum_in_usd} $ {self.date_operation}'


class CryptoPortfolioBalance(models.Model):
    PORTFOLIO_CHOICES = (
        ('crypto', 'crypto'),
        ('stock', 'stock')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='crypto_portfolio_balance')
    portfolio_type = models.CharField(max_length=10, choices=PORTFOLIO_CHOICES, default='crypto')
    sum_in_rub = models.FloatField()
    sum_in_usd = models.FloatField()
    date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return f'{str(self.user)} {str(self.sum_in_rub)} {str(self.sum_in_usd)} {self.date}'

src/crypto/forms.py
from datetime import datetime

from django import forms
from django.core.cache import cache
import logging


logger_debug = logging.getLogger('debug')


class NameModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name + ' ' + obj.ticker


class AddCryptoForm(forms.Form):
    CHOICES_OPERATION_TYPE = [
        (1, 'Покупка'),
        (0, 'Продажа'),
    ]

    token_1 = forms.CharField(label='Первый токен', max_length=6)
    token_2 = forms.CharField(label='Второй токен', max_length=6, initial='USDT', help_text='Если ')
    is_buy_or_sell = forms.ChoiceField(label="Операция", choices=CHOICES_OPERATION_TYPE)
    price_in_currency = forms.FloatField(label='Цена')
    lot = forms.FloatField(label="Количество")
    operation_date = forms.DateField(label="Дата операции",
                                     initial=datetime.now().date,
                                     )

    def clean(self):
        cleaned_data = super().clean()
        token_1 = cleaned_data.get('token_1').upper()
        token_2 = cleaned_data.get('token_2').upper()

        if not (cache.get(f'{token_1}{token_2}')):
            raise forms.ValidationError("Проверьте токены!")


class AddCryptoInvestForm(forms.Form):
    CHOICES_CURRENCY = [
        ('rub', 'Руб'),
        ('usd', 'Usd'),
    ]

    invest_sum_in_rub = forms.FloatField(label='Сумма вложений в рублях')
    invest_sum_in_usd = forms.FloatField(label='Сумма вложений в долларах')
    operation_date = forms.DateField(label="Дата операции",
                                     initial=datetime.now().date,
                                     )

    def clean_operation_date(self):
        data = self.cleaned_data['operation_date']

src/crypto/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from django.conf import settings

from portfolio.services.add_change_in_user_assets import AssetsChange
from portfolio.services.portfolio import CryptoPortfolio, PortfolioMaker
from portfolio.services.portfolio_balance import write_in_db_portfolio_balance
from stocks.utils import DataMixinPortfolio
from .forms import AddCryptoForm, AddCryptoInvestForm
from .models import PersonsCrypto, PersonsTransactions
from .serializers import CryptoTransactionsSerializer
from .tasks import add_transactions_and_update_users_portfolio, update_crypto_transaction, add_invest_sum_task

from deposits.utils import menu, DataMixinMenu

import logging

logger = logging.getLogger('main')
logger_debug = logging.getLogger('debug')


class CryptoPersonBalance(ListView, DataMixinMenu, DataMixinPortfolio):
    model = PersonsCrypto
    template_name = 'crypto/cryptos.html'

    def get_queryset(self):
        return PersonsCrypto.objects.filter(user=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_from_mixin = self.get_user_menu(**kwargs)
        crypto_portfolio_maker = PortfolioMaker(assets_type='crypto', user=self.request.user,
                                                assets=context['object_list'])
        portfolio = crypto_portfolio_maker.portfolio
        context['balance'] = portfolio
        context['assets'] = portfolio.get_info_about_assets()

        return context | context_from_mixin


class PersonCryptoEdit(UpdateView, DataMixinMenu):
    model = PersonsCrypto
    template_name = 'crypto/person_crypto_edit.html'
    fields = ['token', 'lot', 'average_price_in_rub', 'average_price_in_usd']
    success_url = reverse_lazy('crypto:crypto')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_from_mixin = self.get_user_menu(**kwargs)
        return context | context_from_mixin


class PersonCryptoTransaction(ListView, DataMixinMenu):
    model = PersonsTransactions
    paginate_by = 20
    ordering = ['-date_operation']

    def get_queryset(self):
        queryset = PersonsTransactions.objects.filter(user=self.request.user)
        ordering = self.get_ordering()

        if ordering:
            queryset = queryset.order_by(ordering)

        return queryset

    def get_ordering(self):
        # в балансе можно сделать также, тольок здесь прописать логику сортировки
        ordering = self.request.GET.get('ordering', '-date_operation')
        logger_debug.debug(ordering)
        return ordering

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_from_mixin = self.get_user_menu(**kwargs)
        return context | context_from_mixin


class PersonCryptoTransactionEdit(UpdateView, DataMixinMenu):
    model = PersonsTransactions
    template_name = 'crypto/person_crypto_transaction_edit.html'
    fields = ['token_1', 'token_2', 'is_buy_or_sell', 'lot', 'price_in_rub', 'price_in_usd', 'date_operation']
    success_url = reverse_lazy('crypto:person_crypto_transactions')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_from_mixin = self.get_user_menu(**kwargs)
        return context | context_from_mixin

    def form_valid(self, form):
        data = super().form_valid(form)

        transaction = self.get_object()

        # пересчитывает параметры актива в портфеля
        if settings.IN_DOCKER:
            update_crypto_transaction.delay(transaction=transaction)
        else:
            AssetsChange.change_crypto_transaction(changed_transaction=transaction)
        return data


class PersonCryptoTransactionDelete(DeleteView, DataMixinMenu):
    model = PersonsTransactions
    success_url = reverse_lazy('crypto:person_crypto_transactions')
    template_name = 'crypto/confirm_delete.html'

    def form_valid(self, form):
        deleted_object = self.get_object()
        obj = super().form_valid(form)
        AssetsChange.change_crypto_transaction(deleted_object)
        return obj


def add_transaction(request):
    if request.method == 'POST':
        form = AddCryptoForm(request.POST)
        if form.is_valid():
            if settings.IN_DOCKER:
                add_transactions_and_update_users_portfolio.delay(assets_type='crypto',
                                                                  user_id=request.user.id,
                                                                  is_buy_or_sell=int(form.data['is_buy_or_sell']),
                                                                  token_1=form.data['token_1'].lower(),
                                                                  token_2=form.data['token_2'].lower(),
                                                                  lot=float(form.data['lot']),
                                                                  price_currency=
                                                                  float(form.data['price_in_currency']),
                                                                  currency='usd',
                                                                  date_operation=form.data['operation_date'])
            else:
                AssetsChange.add_transaction_in_bd_and_update_users_assets(assets_type='crypto',
                                                                           user=request.user,
                                                                           is_buy_or_sell=
                                                                           int(form.data['is_buy_or_sell']),
                                                                           token_1=form.data['token_1'].lower(),
                                                                           token_2=form.data['token_2'].lower(),
                                                                           lot=float(form.data['lot']),
                                                                           price_currency=
                                                                           float(form.data['price_in_currency']),
                                                                           currency='usd',
                                                                           date_operation=form.data['operation_date'])
            return redirect('crypto:add_crypto')
    else:
        form = AddCryptoForm()
    return render(request, 'crypto/add_crypto.html', {'form': form, 'menu': menu})


def add_invest_sum(request):
    if request.method == 'POST':
        form = AddCryptoInvestForm(request.POST)
        if form.is_valid():
            if settings.IN_DOCKER:
                add_invest_sum_task.delay(invest_sum_in_rub=float(form.data['invest_sum_in_rub']),
                                          invest_sum_in_usd=float(form.data['invest_sum_in_usd']),
                                          date_operation=form.data['operation_date'],
                                          user_id=request.user.id)
            else:
                AssetsChange.add_invest_sum(assets_type='crypto',
                                            invest_sum_in_rub=float(form.data['invest_sum_in_rub']),
                                            invest_sum_in_usd=float(form.data['invest_sum_in_usd']),
                                            date_operation=form.data['operation_date'],
                                            user=request.user)
            return redirect('crypto:add_invest')
    else:
        form = AddCryptoInvestForm()
    return render(request, 'crypto/add_invest.html', {'form': form, 'menu': menu})


# -------------------------------DRF------------------------------------------
class CryptoBalance(generics.ListAPIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, **kwargs):
        balance = CryptoPortfolio(user=request.user)
        return Response(balance.get_info_about_portfolio_and_assets())  # настроить ввод параметров в функцию


class CryptoAddTransactions(generics.CreateAPIView):
    queryset = PersonsTransactions.objects.all()
    serializer_class = CryptoTransactionsSerializer
    permission_classes = (IsAuthenticated,)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class CryptoHistoryTransactions(generics.ListAPIView):
    queryset = PersonsTransactions.objects.all()
    serializer_class = CryptoTransactionsSerializer

src/crypto/templates/crypto/add_crypto.html
{% extends 'base.html' %}
{% block content %}

<p>
    <div>
</div>
</p>

<a class="btn btn-primary" href="{% url 'crypto:crypto' %}" role="button">Баланс</a>

<p>
    <div>
</div>
</p>

<ul class="list-articles">
 <form method="post">
        {%csrf_token%}
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <button type="submit"> Добавить </button>
    </form>

</ul>

{%endblock%}

src/crypto/templates/crypto/add_invest.html
{% extends 'base.html' %}
{% block content %}

<p>
    <div>
</div>
</p>

<a class="btn btn-primary" href="{% url 'crypto:crypto' %}" role="button">Баланс</a>
<a class="btn btn-primary" href="{% url 'crypto:add_crypto' %}" role="button">Добавить актив</a>
<a class="btn btn-primary" href="{% url 'crypto:add_invest' %}" role="button">Внести средства</a>
<a class="btn btn-primary" href="{% url 'crypto:person_crypto_transactions' %}" role="button">Транзакции</a>


<p>
    <div>
</div>
</p>

<ul class="list-articles">
 <form method="post">
        {%csrf_token%}
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <button type="submit"> Добавить </button>
    </form>

</ul>

{%endblock%}

src/crypto/templates/crypto/cryptos.html
{% extends 'base.html' %}
{% load crypto_tags %}
{% block content %}

<p>
<div>

</div>
</p>

<a class="btn btn-primary" href="{% url 'crypto:crypto' %}" role="button">Баланс</a>
<a class="btn btn-primary" href="{% url 'crypto:add_crypto' %}" role="button">Добавить актив</a>
<a class="btn btn-primary" href="{% url 'crypto:add_invest' %}" role="button">Внести средства</a>
<a class="btn btn-primary" href="{% url 'crypto:person_crypto_transactions' %}" role="button">Транзакции</a>


<table class="table">
    <thead>
    <tr>

        <th scope="col">
            <p class="h5">Баланс {{ balance.total_balance_in_rub}} ₽</p>
            <p class="h6"> Прибыль:
                <span class="{% if balance.profit_in_currency_rub >= 0 %}number-greater-than-0{% else %}number-less-than-or-equal-to-0{% endif %}">
                {{ balance.profit_in_currency_rub|add_plus_or_minus }} ₽
            </span>
                <span class="{% if balance.profit_in_percent_rub >= 0 %}number-greater-than-0{% else %}number-less-than-or-equal-to-0{% endif %}">
                {{ balance.profit_in_percent_rub|add_plus_or_minus }} %
            </span>
            </p>
        </th>

        <th scope="col">
            <p class="h5">Баланс {{ balance.total_balance_in_usd}} $</p>
            <p class="h6"> Прибыль:
                <span class="{% if balance.profit_in_currency_usd >= 0 %}number-greater-than-0{% else %}number-less-than-or-equal-to-0{% endif %}">
                {{ balance.profit_in_currency_usd|add_plus_or_minus }} $
            </span>
                <span class="{% if balance.profit_in_percent_usd >= 0 %}number-greater-than-0{% else %}number-less-than-or-equal-to-0{% endif %}">
                    {{ balance.profit_in_percent_usd|add_plus_or_minus }} %
                </span>
            </p>
        </th>

    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="col">
            <p class="h5"> Вложено {{ balance.invest_sum_in_rub }} ₽ </p>
            <p class="h5">
             <span class="{% if balance.profit_invest_in_currency_rub >= 0 %}number-greater-than-0{% else %}number-less-than-or-equal-to-0{% endif %}">
                {{ balance.profit_invest_in_currency_rub|add_plus_or_minus }} ₽
            </span>

                <span class="{% if balance.profit_invest_in_percent_rub >= 0 %}number-greater-than-0{% else %}number-less-than-or-equal-to-0{% endif %}">
                {{ balance.profit_invest_in_percent_rub|add_plus_or_minus }} %
                {{balance.irr_rub}} %
                </span>

        </th>

        <th scope="col">
            <p class="h5"> Вложено {{ balance.invest_sum_in_usd }} $ </p>
            <p class="h5">
                <span class="{% if balance.profit_invest_in_currency_usd < 0 %}number-less-than-or-equal-to-0 {% else %}number-greater-than-0{% endif %}">
                {{ balance.profit_invest_in_currency_usd|add_plus_or_minus }} $
                </span>


                <span class="{% if balance.profit_invest_in_percent_usd >= 0 %}number-greater-than-0{% else %}number-less-than-or-equal-to-0{% endif %}">
                {{ balance.profit_invest_in_percent_usd|add_plus_or_minus }} %
                    {{balance.irr_usd}} %
            </span>
            </p>
        </th>
    </tr>
    </tbody>
</table>


<table class="table">
    <thead>
    <tr>
        <th scope="col"></th>

        <th scope="col">
            <p class="h6">Название</p>
        </th>

        <th scope="col">
            <p class="h6">Количество</p>
        </th>

        <th scope="col">
            <p class="h6">Средняя цена, $</p>
        </th>

        <th scope="col">
            <p class="h6"> Прибыль </p>
        </th>

        <th scope="col">
            <p class="h6"> Цена, $ </p>
        </th>

        <th scope="col">
            <p class="h6"> Стоимость, $ </p>
        </th>

        <th scope="col">
            <p class="h6"> Доля, % </p>
        </th>

        <th scope="col">
        </th>
    </tr>
    </tr>
    </thead>

    <tbody>
    {% for value in assets.values %}
    <tr>
        <th scope="row"> {{ forloop.counter}}</th>
        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ value.name.upper }}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ value.lot}}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ value.average_price_buy }}
                    </div>
                </div>
            </div>
        </td>


        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                         <span class="{% if value.profit_in_currency >= 0 %}number-greater-than-0{% else %}number-less-than-or-equal-to-0{% endif %}">
                    {{ value.profit_in_currency|add_plus_or_minus }} $
                </span>
                        <br>
                        <span class="{% if value.profit_in_percent >= 0 %}number-greater-than-0{% else %}number-less-than-or-equal-to-0{% endif %}">
                    {{ value.profit_in_percent|add_plus_or_minus }} %
                </span>

                    </div>
                </div>
            </div>
        </td>


        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ value.current_price}}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ value.total_balance}}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ value.percent_of_portfolio }}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        <a class="btn btn-primary" href="{% url 'crypto:person_crypto_edit' value.pk %}" role="button">Редактировать</a>
                    </div>
                </div>
            </div>
        </td>

    </tr>
    {% endfor %}
    </tbody>
</table>


{%endblock%}

src/crypto/templates/crypto/person_crypto_transaction_edit.html
{% extends 'base.html' %}
{% block content %}

<p>
<div></div>
</p>


<a class="btn btn-primary" href="{% url 'crypto:crypto' %}" role="button">Баланс</a>
<a class="btn btn-primary" href="{% url 'crypto:add_crypto' %}" role="button">Добавить актив</a>
<a class="btn btn-primary" href="{% url 'crypto:add_invest' %}" role="button">Внести средства</a>
<a class="btn btn-primary" href="{% url 'crypto:person_crypto_transactions' %}" role="button">Транзакции</a>

<p>
<div></div>
</p>


<ul class="list-articles">
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить">
        <a href="{% url 'crypto:person_crypto_transaction_delete' object.pk %}" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">
            <i class="fas fa-times"></i> Удалить
        </a>
    </form>
</ul>


{%endblock%}

src/crypto/templates/crypto/personstransactions_list.html
{% extends 'base.html' %}
{% block content %}


<p>
<div>

</div>
</p>

<a class="btn btn-primary" href="{% url 'crypto:crypto' %}" role="button">Баланс</a>
<a class="btn btn-primary" href="{% url 'crypto:add_crypto' %}" role="button">Добавить актив</a>
<a class="btn btn-primary" href="{% url 'crypto:add_invest' %}" role="button">Внести средства</a>


<table class="table">
    <thead>
    <tr>
        <th scope="col"></th>

        <th scope="col">
            <p class="h6">
                Токен 1

                <a href="?ordering=-token_1">
                    <span class="arrow">&#8593;</span>
                </a>

                <a href="?ordering=token_1">
                    <span class="arrow">&#8595;</span>
                </a>


            </p>
        </th>

        <th scope="col">
            <p class="h6">Токен 2
            <a href="?ordering=-token_2">
                    <span class="arrow">&#8593;</span>
                </a>

                <a href="?ordering=token_2">
                    <span class="arrow">&#8595;</span>
                </a>
            </p>
        </th>

        <th scope="col">
            <p class="h6">Операция
            <a href="?ordering=-is_buy_or_sell">
                    <span class="arrow">&#8593;</span>
                </a>

                <a href="?ordering=is_buy_or_sell">
                    <span class="arrow">&#8595;</span>
                </a>
            </p>
        </th>

        <th scope="col">
            <p class="h6">Цена в $
            <a href="?ordering=-price_in_usd">
                    <span class="arrow">&#8593;</span>
                </a>

                <a href="?ordering=price_in_rub">
                    <span class="arrow">&#8595;</span>
                </a>
            </p>
        </th>

        <th scope="col">
            <p class="h6"> Цена в Р
            <a href="?ordering=-price_in_rub">
                    <span class="arrow">&#8593;</span>
                </a>

                <a href="?ordering=price_in_rub">
                    <span class="arrow">&#8595;</span>
                </a>
            </p>
        </th>

        <th scope="col">
            <p class="h6"> Количество
            <a href="?ordering=-lot">
                    <span class="arrow">&#8593;</span>
                </a>

                <a href="?ordering=lot">
                    <span class="arrow">&#8595;</span>
                </a>
            </p>
        </th>

        <th scope="col">
            <p class="h6"> Дата операции
            <a href="?ordering=-date_operation">
                    <span class="arrow">&#8593;</span>
                </a>

                <a href="?ordering=date_operation">
                    <span class="arrow">&#8595;</span>
                </a>
            </p>
        </th>
        <th scope="col">
        </th>
    </tr>
    </tr>
    </thead>
    <tbody>
    {% for transaction in object_list %}
    <tr>
        <th scope="row"> {{ forloop.counter}}</th>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ transaction.token_1.upper }}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ transaction.token_2.upper }}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {% if transaction.is_buy_or_sell %}
                        <div> Покупка</div>
                        {% else %}
                        <div>Продажа</div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </td>


        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ transaction.price_in_usd}}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ transaction.price_in_rub }}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ transaction.lot }}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        {{ transaction.date_operation }}
                    </div>
                </div>
            </div>
        </td>

        <td>
            <div class="container text-left">
                <div class="row">
                    <div class="col">
                        <a class="btn btn-primary"
                           href="{% url 'crypto:person_crypto_transaction_edit' transaction.pk %}"
                           role="button">Редактировать</a>
                    </div>
                </div>
            </div>
        </td>


    </tr>
    {% endfor %}
    </tbody>
</table>



<div class="pagination justify-content-center">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <li class="page-item disabled">
            <span class="page-link"> Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</div>


{%endblock%}